### PR TITLE
Fixed bugs after IEXtrading endpoing 12/01 upgrade (#105)

### PR DESCRIPTION
**Pull request by JoseMariaBernad**
# Description

The Dec 01 upgrade of IEXCloud enpoints broke many enpoints that started to return some dates as linux epoch values. Also broke some dates that started to appear as 0000-00-00 where previously there were null values.

Fixes # (105)

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Arham4 — APPROVED** [review]

**Comment by esodot** [comment]
Great thank you for approving. Looking forward to the merge.

**Comment by JoseMariaBernad** [comment]
Yes, it looks like it is failing for other endpoints such as ExchangeSymbol, Chart or FundOwnership. There seem to be a bunch of new properties after the 12/01 update of IEX cloud. I don't use those, so I did not fix them.

**Comment by WojciechZankowski** [comment]
> Yes, it looks like it is failing for other endpoints such as ExchangeSymbol, Chart or FundOwnership. There seem to be a bunch of new properties after the 12/01 update of IEX cloud. I don't use those, so I did not fix them.

I will add new properties today and then merge your PR

**Comment by esodot** [comment]
> Yes, it looks like it is failing for other endpoints such as ExchangeSymbol, Chart or FundOwnership. There seem to be a bunch of new properties after the 12/01 update of IEX cloud. I don't use those, so I did not fix them.

yes they changed a lot

**Pull request merged**
