### PR TITLE
SentimentRequestBuilder should build a single RestRequest<Sentiment>, instead of RestRequest<List<Sentiment>>

### PR DESCRIPTION
**Pull request by 10shibu**
# Description

The Sentiment Rest Response will only return one sentiment response not a list: https://iexcloud.io/docs/api/#social-sentiment

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 10shibu** [comment]
I'm not sure should I create a new fork each time or can keep doing on one branch. Thanks for reviewing this.

**Comment by swarwick** [comment]
Hold on this, it looks like the minute request is indeed a list

**Comment by 10shibu** [comment]
Yes, with minute as SentimentType, the returned response is a list

**Comment by WojciechZankowski** [comment]
@10shibu I created DailySentimentRequestBuilder. Nobody likes to do 

```java
sentiments.get(0);
```

Here is new request builder:

```java
final Sentiment result = cloudClient.executeRequest(new DailySentimentRequestBuilder()
		.withSymbol("AAPL")
		.withDate(LocalDate.of(2019, 10, 12))
		.build());
```

You can check commit here: https://github.com/WojciechZankowski/iextrading4j/commit/88833575fab6ea2d7e363c6ec160be46d4937dd0

I will release it probably during this week.


Cheers,

Wojtek

**Pull request closed without merging**
